// ============================================================
// EXERCISE REMINDER MODEL
// Stores exercise/workout reminders for users
// DBMS Concepts: Foreign Key (userId), NOT NULL, Referential Integrity
// ============================================================

const mongoose = require('mongoose');

const exerciseReminderSchema = new mongoose.Schema({
  // exerciseId is auto-generated by MongoDB as _id (Primary Key)
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',                               // FOREIGN KEY reference to User
    required: [true, 'User ID is required'],   // NOT NULL + Referential Integrity
    index: true
  },
  exerciseName: {
    type: String,
    required: [true, 'Exercise name is required'],  // NOT NULL
    trim: true,
    maxlength: [100, 'Exercise name cannot exceed 100 characters']
  },
  exerciseType: {
    type: String,
    enum: ['cardio', 'strength', 'flexibility', 'balance', 'sports', 'other'],
    default: 'cardio'
  },
  duration: {
    type: Number,    // Duration in minutes
    default: 30,
    min: 5,
    max: 300
  },
  reminderTime: {
    type: String,
    required: [true, 'Reminder time is required'],  // NOT NULL
    trim: true
  },
  frequency: {
    type: String,
    enum: ['once', 'daily', 'weekly', 'weekdays', 'weekends'],
    default: 'daily'
  },
  isCompleted: {
    type: Boolean,
    default: false
  },
  completedAt: {
    type: Date,
    default: null
  },
  isActive: {
    type: Boolean,
    default: true
  },
  calories: {
    type: Number,
    default: 0,
    min: 0
  },
  notes: {
    type: String,
    trim: true,
    maxlength: [300, 'Notes cannot exceed 300 characters'],
    default: ''
  }
}, {
  timestamps: true
});

// COMPOUND INDEX for user-specific exercise queries
exerciseReminderSchema.index({ userId: 1, isActive: 1 });
exerciseReminderSchema.index({ userId: 1, createdAt: -1 });

module.exports = mongoose.model('ExerciseReminder', exerciseReminderSchema);
