// ============================================================
// HEALTH TIP MODEL
// Stores health tips categorized by wellness topics
// DBMS Concepts: Primary Key, NOT NULL, ENUM validation
// ============================================================

const mongoose = require('mongoose');

const healthTipSchema = new mongoose.Schema({
  // tipId is auto-generated by MongoDB as _id (Primary Key)
  category: {
    type: String,
    required: [true, 'Category is required'],  // NOT NULL
    enum: {
      values: ['fitness', 'nutrition', 'mental_health', 'sleep', 'hydration'],
      message: 'Category must be: fitness, nutrition, mental_health, sleep, or hydration'
    },
    index: true
  },
  content: {
    type: String,
    required: [true, 'Tip content is required'],  // NOT NULL
    trim: true,
    minlength: [10, 'Tip must be at least 10 characters'],
    maxlength: [500, 'Tip cannot exceed 500 characters']
  },
  title: {
    type: String,
    required: [true, 'Tip title is required'],
    trim: true,
    maxlength: [100, 'Title cannot exceed 100 characters']
  },
  icon: {
    type: String,
    default: '💡'
  },
  isActive: {
    type: Boolean,
    default: true
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  }
}, {
  timestamps: true
});

// INDEX for category-based queries
healthTipSchema.index({ category: 1, isActive: 1 });

/**
 * STATIC METHOD: Get random tip from a specific category
 * Uses MongoDB aggregation $sample for random selection
 */
healthTipSchema.statics.getRandomTip = async function(category = null) {
  const match = { isActive: true };
  if (category) match.category = category;

  const tips = await this.aggregate([
    { $match: match },
    { $sample: { size: 1 } }  // Random selection
  ]);

  return tips.length > 0 ? tips[0] : null;
};

/**
 * STATIC METHOD: Get daily tips (one from each category)
 */
healthTipSchema.statics.getDailyTips = async function() {
  const categories = ['fitness', 'nutrition', 'mental_health', 'sleep', 'hydration'];
  const tips = [];

  for (const category of categories) {
    const tip = await this.getRandomTip(category);
    if (tip) tips.push(tip);
  }

  return tips;
};

module.exports = mongoose.model('HealthTip', healthTipSchema);
