// ============================================================
// MEDICINE REMINDER MODEL
// Stores medicine reminder data with user reference
// DBMS Concepts: Foreign Key (userId), NOT NULL, Referential Integrity
// ============================================================

const mongoose = require('mongoose');

const medicineReminderSchema = new mongoose.Schema({
  // reminderId is auto-generated by MongoDB as _id (Primary Key)
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',                              // FOREIGN KEY reference to User
    required: [true, 'User ID is required'],  // NOT NULL + Referential Integrity
    index: true                               // INDEX for faster lookups
  },
  medicineName: {
    type: String,
    required: [true, 'Medicine name is required'],  // NOT NULL
    trim: true,
    maxlength: [100, 'Medicine name cannot exceed 100 characters']
  },
  dosage: {
    type: String,
    required: [true, 'Dosage is required'],         // NOT NULL
    trim: true
  },
  time: {
    type: String,
    required: [true, 'Reminder time is required'],  // NOT NULL
    trim: true
  },
  frequency: {
    type: String,
    required: [true, 'Frequency is required'],      // NOT NULL
    enum: ['once', 'daily', 'twice_daily', 'weekly', 'monthly'],
    default: 'daily'
  },
  notes: {
    type: String,
    trim: true,
    maxlength: [500, 'Notes cannot exceed 500 characters'],
    default: ''
  },
  isCompleted: {
    type: Boolean,
    default: false
  },
  completedAt: {
    type: Date,
    default: null
  },
  isActive: {
    type: Boolean,
    default: true
  }
}, {
  timestamps: true
});

// COMPOUND INDEX for efficient user-specific queries
medicineReminderSchema.index({ userId: 1, isActive: 1 });
medicineReminderSchema.index({ userId: 1, createdAt: -1 });

module.exports = mongoose.model('MedicineReminder', medicineReminderSchema);
