// ============================================================
// USER MODEL
// Stores user account information with secure password hashing
// DBMS Concepts: Primary Key, UNIQUE constraint, NOT NULL
// ============================================================

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const userSchema = new mongoose.Schema({
  // userId is auto-generated by MongoDB as _id (Primary Key)
  name: {
    type: String,
    required: [true, 'Name is required'],      // NOT NULL constraint
    trim: true,
    minlength: [2, 'Name must be at least 2 characters'],
    maxlength: [50, 'Name cannot exceed 50 characters']
  },
  email: {
    type: String,
    required: [true, 'Email is required'],      // NOT NULL constraint
    unique: true,                                // UNIQUE constraint
    lowercase: true,
    trim: true,
    match: [/^\S+@\S+\.\S+$/, 'Please enter a valid email']
  },
  password: {
    type: String,
    required: [true, 'Password is required'],   // NOT NULL constraint
    minlength: [6, 'Password must be at least 6 characters'],
    select: false  // Don't include password in queries by default
  },
  role: {
    type: String,
    enum: ['user', 'admin'],
    default: 'user'
  },
  dailyWaterGoal: {
    type: Number,
    default: 2000,  // Default 2000ml (2 liters) daily goal
    min: 500,
    max: 10000
  },
  streak: {
    type: Number,
    default: 0
  },
  lastActiveDate: {
    type: Date,
    default: Date.now
  },
  profileImage: {
    type: String,
    default: ''
  }
}, {
  timestamps: true  // Adds createdAt and updatedAt automatically
});

/**
 * Pre-save middleware: Hash password before saving to database
 * This ensures passwords are never stored in plain text
 */
userSchema.pre('save', async function(next) {
  // Only hash the password if it has been modified
  if (!this.isModified('password')) return next();
  
  // Generate salt and hash password (10 rounds)
  const salt = await bcrypt.genSalt(10);
  this.password = await bcrypt.hash(this.password, salt);
  next();
});

/**
 * Instance method: Compare entered password with stored hash
 * @param {string} enteredPassword - Password to verify
 * @returns {boolean} - True if passwords match
 */
userSchema.methods.comparePassword = async function(enteredPassword) {
  return await bcrypt.compare(enteredPassword, this.password);
};

module.exports = mongoose.model('User', userSchema);
