// ============================================================
// WATER TRACKER MODEL
// Tracks daily water intake entries for each user
// DBMS Concepts: Foreign Key (userId), NOT NULL, Timestamps
// ============================================================

const mongoose = require('mongoose');

const waterTrackerSchema = new mongoose.Schema({
  // entryId is auto-generated by MongoDB as _id (Primary Key)
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',                              // FOREIGN KEY reference to User
    required: [true, 'User ID is required'],  // NOT NULL + Referential Integrity
    index: true
  },
  amount: {
    type: Number,
    required: [true, 'Water amount is required'],  // NOT NULL
    min: [1, 'Amount must be at least 1ml'],
    max: [5000, 'Amount cannot exceed 5000ml per entry']
  },
  unit: {
    type: String,
    enum: ['ml', 'oz', 'cups', 'liters'],
    default: 'ml'
  },
  timestamp: {
    type: Date,
    default: Date.now,    // Automatically records when water was logged
    index: true
  }
}, {
  timestamps: true
});

// COMPOUND INDEX for efficient daily water queries per user
waterTrackerSchema.index({ userId: 1, timestamp: -1 });

/**
 * STATIC METHOD: Aggregation query to get daily water total for a user
 * Demonstrates MongoDB aggregation pipeline (equivalent to SQL GROUP BY)
 */
waterTrackerSchema.statics.getDailyTotal = async function(userId, date) {
  const startOfDay = new Date(date);
  startOfDay.setHours(0, 0, 0, 0);
  
  const endOfDay = new Date(date);
  endOfDay.setHours(23, 59, 59, 999);

  const result = await this.aggregate([
    {
      $match: {
        userId: new mongoose.Types.ObjectId(userId),
        timestamp: { $gte: startOfDay, $lte: endOfDay }
      }
    },
    {
      $group: {
        _id: null,
        totalAmount: { $sum: '$amount' },   // SUM aggregation
        entryCount: { $sum: 1 }             // COUNT aggregation
      }
    }
  ]);

  return result.length > 0 ? result[0] : { totalAmount: 0, entryCount: 0 };
};

/**
 * STATIC METHOD: Get weekly water intake data
 * Uses aggregation pipeline with date grouping
 */
waterTrackerSchema.statics.getWeeklyData = async function(userId) {
  const sevenDaysAgo = new Date();
  sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
  sevenDaysAgo.setHours(0, 0, 0, 0);

  return await this.aggregate([
    {
      $match: {
        userId: new mongoose.Types.ObjectId(userId),
        timestamp: { $gte: sevenDaysAgo }
      }
    },
    {
      $group: {
        _id: {
          $dateToString: { format: '%Y-%m-%d', date: '$timestamp' }
        },
        totalAmount: { $sum: '$amount' },
        entries: { $sum: 1 }
      }
    },
    { $sort: { _id: 1 } }  // ORDER BY date ascending
  ]);
};

module.exports = mongoose.model('WaterTracker', waterTrackerSchema);
